version: '3'

services:
  php:
    build:
      context: './docker/php'
    volumes:
      - ./:/project
    command: php -d memory_limit=512M /project/main.php
    environment:
      CLASS: '\Ghash\Sol1'
